server:
  port: 9005
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s

spring:
  application:
    name: notification-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/PolarBookshop
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: user
    password: password
    url: r2dbc:postgresql://localhost:5432/bookshopdb_notification
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5432/bookshopdb_notification
  cloud:
    function:
      definition: handleOrderEvent;handleDeliveryEvent
    stream:
      bindings:
        handleOrderEvent-in-0:
          destination: order
          group: ${spring.application.name}
        handleDeliveryEvent-in-0:
          destination: delivery
          group: ${spring.application.name}
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s

brevo:
  uri: https://api.brevo.com
  api-key: ''